# Generated by Django 3.2.6 on 2021-12-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=45, null=True)),
                ('create_date', models.DateField()),
            ],
        ),
    ]
