# Generated by Django 3.2.6 on 2021-12-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(height_field=161, null=True, upload_to='', width_field=161),
        ),
    ]
